### ISSUE TITLE
Implimenting driver in C

### ISSUE THREAD

**Issue by DanielFjeld** [FelipeCalliari/MMC5983MA#2]
I am trying to get 1000Hz data from the sensor with the INT pin trigring an interrupt using C on an microcontroller. do you have any idea what registers I need to set and what data to send in order to make it do what I want?

**Comment by FelipeCalliari** [comment]
Hi @DanielFjeld,

In order to get 1000 Hz you must set BW = 11 and CM_Freq = 111, after that you must enable "Continuous Measurement Mode", ie, Cmm_en = 1. After that you just need to check INT (which tells when new data is ready) and read the values. 

There is an implementation for Arduino, check the link below:
https://github.com/sparkfun/SparkFun_MMC5983MA_Magnetometer_Arduino_Library

**Comment by FelipeCalliari** [comment]
Hi @DanielFjeld,

Ok, here are the steps with registers and values.

1. Soft Reset (SW_RST) => write to register `reg[0x0a] = (1 << 7)`
2. Wait for 15 ms
3. Set bandwidth => write to register `reg[0x0a] = 3` (BW=0b11 => 800 Hz)
4. Set continuous measurement frequency => write to register `reg[0x0b] = 7` (CM_FREQ=0b111 => 1000 Hz)
5. You can enable or not automatic SET/RESET (to get more accurate measurements) => write to register `reg[0x09] = (1 << 5)` (Auto_SR_en=1)
6. Enabled continuous mode => write to register `reg[0x0b] = (1 << 3)` (CMM_EN=1)
7. Finally enable the interrupt (INT) => write to register `reg[0x09] = (1 << 2)` (INT_meas_done_en=1)

After that, your microcontroller should execute a function to read the measurement every time the interrupt is triggered.
